{{- if .Values.mssql.developerEdition }}
{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-mssql-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{ if .Values.saPassword }}
  SA_PASSWORD: {{ default "" .Values.saPassword | b64enc | quote }}
  {{ else }}
  SA_PASSWORD: {{ printf "%s%s" "{{randAlphaNum 13}}" "{{randNumeric 2}}" | b64enc | quote }}
  {{ end }}
{{ end }}
{{ end }}